# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: 'devcontainers'
    directory: '/.devcontainer'
    groups:
      all:
        patterns:
          - '*'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    groups:
      all:
        patterns:
          - '*'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/'
    groups:
      all:
        patterns:
          - '*'
    schedule:
      interval: 'weekly'
    versioning-strategy: 'widen'
  - package-ecosystem: 'uv'
    allow:
    - dependency-type: 'all'
    directory: '/'
    groups:
      all:
        patterns:
          - '*'
    schedule:
      interval: 'weekly'
