# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

# Configuration of the Python environment to be used
python:
   install:
   - requirements: requirements/docs.txt
   - requirements: docs/requirements.txt
   - method: pip
     path: .

# Configuration for Sphinx documentation
sphinx:
   configuration: docs/conf.py
   fail_on_warning: true
