trainer:
  accelerator: gpu
  devices: 1
  min_epochs: 20
  max_epochs: 100
  benchmark: true
  enable_progress_bar: true
experiment:
  task: l7irish
  module:
    loss: ce
    model: unet
    backbone: resnet18
    weights: imagenet
    learning_rate: 0.0001
    learning_rate_schedule_patience: 6
    verbose: false
    in_channels: 9
    num_classes: 5
    num_filters: 256
    ignore_index: null
    segmentation_model: unet
  datamodule:
    root: /projects/dali/data/l7irish
    batch_size: 64
    patch_size: 1024
    num_workers: 4
  name: unet_resnet18_0.0001_ce_imagenet
config_file: conf/l7irish.yaml
program:
  seed: 0
  output_dir: output/l7irish_experiments
  data_dir: /projects/dali/data/l7irish
  log_dir: output/l7irish_experiments/logs
  overwrite: false
