seed_everything: 0
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 60
  precision: 16-mixed
  benchmark: true
  log_every_n_steps: 10
  enable_progress_bar: false
  limit_val_batches: 0
  num_sanity_val_steps: 0
  default_root_dir: output/ssl_benchmarking/simclr_vit_small
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: output/ssl_benchmarking/simclr_vit_small/checkpoints
        filename: epoch{epoch:03d}
        auto_insert_metric_name: false
        every_n_epochs: 20
        save_top_k: -1
        save_last: true
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
  logger:
    - class_path: lightning.pytorch.loggers.CSVLogger
      init_args:
        save_dir: output/ssl_benchmarking/simclr_vit_small
        name: csv
        version: ''
        flush_logs_every_n_steps: 50
model:
  class_path: SimCLR
  init_args:
    model: vit_small_patch16_224
    in_channels: 13
    version: 2
    lr: 1.5
    size: 224
    memory_bank_size: 0
data:
  class_path: EuroSATDataModule
  init_args:
    batch_size: 128
    num_workers: 3
  dict_kwargs:
    root: data/eurosat
    download: false
