blank_issues_enabled: true
contact_links:
  - name: ❓ Questions
    url: https://github.com/microsoft/torchgeo/discussions
    about: Ask questions or discuss ideas with other TorchGeo users
  - name: 💬 Chat
    url: https://join.slack.com/t/torchgeo/shared_invite/zt-22rse667m-eqtCeNW0yI000Tl4B~2PIw
    about: Chat with fellow TorchGeo users and developers on Slack
