module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  model: "unet"
  backbone: "resnet18"
  weights: null
  in_channels: 12
  num_classes: 13
  loss: "ce"
  ignore_index: -999
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6
  weight_decay: 0
  freeze_backbone: True

datamodule:
  _target_: torchgeo.datamodules.AgriFieldNetDataModule
  root: "data/agrifieldnet"
  batch_size: 32
  patch_size: 256
  num_workers: 10
  download: True

trainer:
  _target_: lightning.pytorch.Trainer
  min_epochs: 20
  max_epochs: 100

program:
  seed: 2
  output_dir: "outputs"
  log_dir: "logs"
  overwrite: True
  experiment_name: agrifieldnet
