trainer:
  min_epochs: 15
  max_epochs: 40
model:
  class_path: MultiLabelClassificationTask
  init_args:
    loss: "bce"
    model: "resnet18"
    lr: 1e-3
    patience: 6
    weights: null
    in_channels: 14
    num_classes: 19
data:
  class_path: BigEarthNetDataModule
  init_args:
    batch_size: 128
    num_workers: 4
  dict_kwargs:
    root: "data/bigearthnet"
    bands: "all"
    num_classes: ${model.init_args.num_classes}
