trainer:
  gpus: 1
  min_epochs: 10
  max_epochs: 40
  benchmark: True
experiment:
  task: "bigearthnet"
  module:
    loss: "bce"
    model: "resnet18"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    weights: "random"
    in_channels: 14
    num_classes: 19
  datamodule:
    root: "data/bigearthnet"
    bands: "all"
    num_classes: ${experiment.module.num_classes}
    batch_size: 128
    num_workers: 4
