module:
  _target_: torchgeo.trainers.MultiLabelClassificationTask
  loss: "bce"
  model: "resnet18"
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6
  weights: null
  in_channels: 14
  num_classes: 19

datamodule:
  _target_: torchgeo.datamodules.BigEarthNetDataModule
  root: "data/bigearthnet"
  bands: "all"
  num_classes: ${module.num_classes}
  batch_size: 128
  num_workers: 4

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices: 1
  min_epochs: 15
  max_epochs: 40
