trainer:
  gpus: 1  # single GPU training
  min_epochs: 10
  max_epochs: 40
  benchmark: True

experiment:
  task: "bigearthnet"
  module:
    loss: "bce"
    classification_model: "resnet18"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    in_channels: 14
  datamodule:
    batch_size: 128
    num_workers: 6
    bands: "all"
