trainer:
  gpus: 1
  min_epochs: 20
  max_epochs: 100
  benchmark: True
experiment:
  task: "ssl"
  name: "test_byol"
  module:
    model: "byol"
    backbone: "resnet18"
    input_channels: 4
    weights: imagenet
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
  datamodule:
    root: "data/chesapeake/cvpr"
    train_splits:
      - "de-train"
    val_splits:
      - "de-val"
    test_splits:
      - "de-test"
    batch_size: 64
    num_workers: 4
