trainer:
  accelerator: gpu
  devices: 1
  min_epochs: 20
  max_epochs: 100
  benchmark: True
  precision: 16
  limit_val_batches: 0.0
experiment:
  trainer: "byol"
  module:
    in_channels: null
    backbone: "resnet18"
    weights: True
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    optimizer: "Adam"
