trainer:
  gpus: 1  # single GPU training
  min_epochs: 20
  max_epochs: 100
  benchmark: True

experiment:
  task: "chesapeake_cvpr"
  name: "chesapeake_cvpr_example"
  module:
    loss: "ce"  # cross entropy loss
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: null  # use ImageNet weight initialization
    encoder_output_stride: 16
    optimizer: "adamw"
    learning_rate: 1e-2
    learning_rate_schedule_patience: 6
    class_set: 5
  datamodule:
    batch_size: 64
    num_workers: 6
    train_state: "de" # train/val/test in Delaware
