trainer:
  gpus: 1
  min_epochs: 15
experiment:
  task: cowc_counting
  name: cowc_counting_test
  module:
    model: resnet18
    learning_rate: 1e-3
    learning_rate_schedule_patience: 2
    pretrained: True
  datamodule:
    root_dir: "data/cowc_counting"
    seed: 0
    batch_size: 32
    num_workers: 4
