module:
  _target_: torchgeo.trainers.RegressionTask
  model: "resnet18"
  weights: null
  num_outputs: 1
  in_channels: 3
  learning_rate: 1e-3
  learning_rate_schedule_patience: 2

datamodule:
  _target_: torchgeo.datamodules.TropicalCycloneDataModule
  root: "data/cyclone"
  batch_size: 32
  num_workers: 4

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices: 1
  min_epochs: 15
  max_epochs: 40
