module:
  _target_: RegressionTask
  model: "resnet18"
  weights: null
  num_outputs: 1
  in_channels: 3
  learning_rate: 1e-3
  learning_rate_schedule_patience: 2

datamodule:
  _target_: TropicalCycloneDataModule
  root: "data/cyclone"
  batch_size: 32
  num_workers: 4