trainer:
  min_epochs: 15
  max_epochs: 40
model:
  class_path: RegressionTask
  init_args:
    model: "resnet18"
    weights: null
    num_outputs: 1
    in_channels: 3
    lr: 1e-3
    patience: 2
data:
  class_path: TropicalCycloneDataModule
  init_args:
    batch_size: 32
    num_workers: 4
  dict_kwargs:
    root: "data/cyclone"
