program:  # These are the arguments that define how the train.py script works
  seed: 1337
  overwrite: True

experiment:
  task: "cyclone"
  name: cyclone_test
  module:
    model: "resnet18"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 2
  datamodule:
    batch_size: 32
    num_workers: 4

trainer:
  min_epochs: 15
  gpus: 1
