trainer:
  gpus: 1
  min_epochs: 15
experiment:
  task: "cyclone"
  name: "cyclone_test"
  module:
    model: "resnet18"
    weights: null
    num_outputs: 1
    in_channels: 3
    learning_rate: 1e-3
    learning_rate_schedule_patience: 2
  datamodule:
    root: "data/cyclone"
    seed: 0
    batch_size: 32
    num_workers: 4
