trainer:
  min_epochs: 15
  max_epochs: 40
model:
  class_path: SemanticSegmentationTask
  init_args:
    loss: "ce"
    model: "unet"
    backbone: "resnet18"
    weights: null
    lr: 1e-3
    patience: 6
    in_channels: 3
    num_classes: 7
    num_filters: 1
    ignore_index: null
data:
  class_path: DeepGlobeLandCoverDataModule
  init_args:
    batch_size: 1
    patch_size: 64
    val_split_pct: 0.5
    num_workers: 0
  dict_kwargs:
    root: "data/deepglobelandcover"
