module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  loss: "ce"
  model: "unet"
  backbone: "resnet18"
  weights: null
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6
  verbose: false
  in_channels: 3
  num_classes: 7
  num_filters: 1
  ignore_index: null

datamodule:
  _target_: torchgeo.datamodules.DeepGlobeLandCoverDataModule
  root: "data/deepglobelandcover"
  batch_size: 1
  patch_size: 64
  val_split_pct: 0.5
  num_workers: 0

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices: 1
  min_epochs: 15
  max_epochs: 40