experiment:
  task: "etci2021"
  module:
    loss: "ce"
    model: "unet"
    backbone: "resnet18"
    weights: "imagenet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    in_channels: 6
    num_classes: 2
    ignore_index: 0
  datamodule:
    root: "data/etci2021"
    batch_size: 32
    num_workers: 4
