experiment:
  task: "gid15"
  module:
    loss: "ce"
    model: "unet"
    backbone: "resnet18"
    weights: null
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    verbose: false
    in_channels: 3
    num_classes: 16
    num_filters: 1
    ignore_index: null
  datamodule:
    root: "data/gid15"
    num_tiles_per_batch: 16
    num_patches_per_tile: 16
    patch_size: 64
    val_split_pct: 0.5
    num_workers: 0
