program:
  overwrite: True


trainer:
  gpus: 1
  min_epochs: 5
  max_epochs: 100
  benchmark: True
  log_every_n_steps: 2

experiment:
  task: "inria"
  name: "inria_test"
  module:
    loss: "ce"
    model: "unet"
    backbone: "resnet18"
    weights: "imagenet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    in_channels: 3
    num_classes: 2
    ignore_index: null
  datamodule:
    root: "data/inria"
    num_tiles_per_batch: 2
    num_patches_per_tile: 4
    patch_size: 512
    num_workers: 32
