trainer:
  min_epochs: 15
  max_epochs: 40
model:
  class_path: SemanticSegmentationTask
  init_args:
    loss: "ce"
    model: "unet"
    backbone: "resnet18"
    weights: true
    lr: 1e-3
    patience: 6
    in_channels: 3
    num_classes: 2
    ignore_index: null
data:
  class_path: InriaAerialImageLabelingDataModule
  init_args:
    batch_size: 1
    patch_size: 512
    num_workers: 32
  dict_kwargs:
    root: "data/inria"
