module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  loss: "ce"
  model: "unet"
  backbone: "resnet18"
  weights: "imagenet"
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6
  in_channels: 3
  num_classes: 2
  ignore_index: null

datamodule:
  _target_: torchgeo.datamodules.InriaAerialImageLabelingDataModule
  root: "data/inria"
  batch_size: 1
  patch_size: 512
  num_workers: 32

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices: 1
  min_epochs: 15
  max_epochs: 40