trainer:
  accelerator: gpu
<<<<<<< HEAD
  devices: 2
=======
  devices: 1
>>>>>>> 7fd28499ac1019ca7f63fd3b4739a9c2fae5db88
  min_epochs: 20
  max_epochs: 100
  benchmark: True
  enable_progress_bar: True
experiment:
  task: "l7irish"
  module:
    loss: "ce"
    model: "unet"
    backbone: "resnet18"
    weights: "null"
    learning_rate: 1e-2
    learning_rate_schedule_patience: 6
    verbose: false
    in_channels: 9
    num_classes: 5
    num_filters: 256
    ignore_index: null
  datamodule:
    root: "/projects/dali/data/l7irish"
    batch_size: 64
    patch_size: 512
<<<<<<< HEAD
<<<<<<< HEAD
    num_workers: 1
=======
    num_workers: 1
>>>>>>> 7fd28499ac1019ca7f63fd3b4739a9c2fae5db88
=======
    num_workers: 1
>>>>>>> 7fd28499ac1019ca7f63fd3b4739a9c2fae5db88
