trainer:
  accelerator: gpu
  devices: 1
  min_epochs: 20
  max_epochs: 100
  benchmark: True
experiment:
  task: "l7irish"
  ipc: "host"
  module:
    loss: "ce"
    model: "unet"
    backbone: "resnet18"
    weights: "imagenet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    verbose: false
    in_channels: 9
    num_classes: 5
    num_filters: 256
    ignore_index: null
  datamodule:
    root: "/scratch.local/yichia3/l7irish_cog_3857"
    batch_size: 64
    patch_size: 256
    num_workers: 20
