module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  model: "unet"
  backbone: "resnet18"
  weights: null
  in_channels: 9
  num_classes: 5
  loss: "ce"
  class_weights: [0, 0.90484679, 0.00920825, 0.05944526, 0.02649971]
  ignore_index: 0
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6

datamodule:
  _target_: torchgeo.datamodules.L7IrishDataModule
  root: "data/l7irish"
  batch_size: 64
  patch_size: 224
  num_workers: 16

trainer:
  _target_: lightning.pytorch.Trainer
  min_epochs: 20
  max_epochs: 100
