module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  model: "unet"
  backbone: "resnet18"
  weights: null
  in_channels: 9
  num_classes: 5
  loss: "ce"
  ignore_index: 0
  lr: 1e-3
  patience: 6

datamodule:
  _target_: torchgeo.datamodules.L7IrishDataModule
  root: "data/l7irish"
  batch_size: 64
  patch_size: 224
  num_workers: 16

trainer:
  _target_: lightning.pytorch.Trainer
  min_epochs: 20
  max_epochs: 100
