module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  model: "unet"
  backbone: "resnet18"
  weights: null
  in_channels: 11
  num_classes: 5
  loss: "ce"
  class_weights: [0, 0.84585444, 0.02586814, 0.08889015, 0.03938727]
  ignore_index: 0
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6

datamodule:
  _target_: torchgeo.datamodules.L8BiomeDataModule
  root: "data/l8biome"
  batch_size: 64
  patch_size: 224
  num_workers: 16

trainer:
  _target_: lightning.pytorch.Trainer
  min_epochs: 20
  max_epochs: 100
