module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  loss: "ce"
  model: "unet"
  backbone: "resnet18"
  weights: true
  learning_rate: 1e-4
  learning_rate_schedule_patience: 6
  in_channels: 11
  num_classes: 5
  num_filters: 64
  ignore_index: 0
  weight_decay: 0

datamodule:
  _target_: torchgeo.datamodules.L8BiomeTileDataModule
  root: "/home/calebrobinson/ssdprivate/data/L8BiomeSimple/"
  batch_size: 32
  patch_size: 256
  train_batches_per_epoch: 2000
  val_batches_per_epoch: 200
  num_workers: 6

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices:
    - 3
  min_epochs: 15
  max_epochs: 100

program:
  seed: 0
  output_dir: output/l8biome/
  log_dir: logs/l8biome/
  overwrite: True
  experiment_name: unet_imagenet_lr1e-4_wd0