trainer:
  gpus: 1
  min_epochs: 20
  max_epochs: 100
  benchmark: True
experiment:
  task: "landcoverai"
  module:
    loss: "ce"
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    in_channels: 3
    num_classes: 6
    num_filters: 256
    ignore_index: null
  datamodule:
    root_dir: "data/landcoverai"
    batch_size: 32
    num_workers: 4
