trainer:
  gpus: 1  # single GPU training
  min_epochs: 20
  max_epochs: 100
  benchmark: True

experiment:
  task: "landcoverai"
  module:
    loss: "ce"
    segmentation_model: "deeplabv3+"
    encoder_name: "resnet18"
    encoder_weights: null
    encoder_output_stride: 16
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
  datamodule:
    batch_size: 32
    num_workers: 6
