module:
  _target_: SemanticSegmentationTask
  loss: "ce"
  model: "deeplabv3+"
  backbone: "resnet34"
  weights: "imagenet"
  learning_rate: 1e-3
  learning_rate_schedule_patience: 2
  in_channels: 4
  num_classes: 14
  num_filters: 64
  ignore_index: null

datamodule:
  _target_: NAIPChesapeakeDataModule
  naip_root: "data/naip"
  chesapeake_root: "data/chesapeake/BAYWIDE"
  batch_size: 32
  num_workers: 4
  patch_size: 32