trainer:
  min_epochs: 15
  max_epochs: 40
model:
  class_path: SemanticSegmentationTask
  init_args:
    loss: "ce"
    model: "deeplabv3+"
    backbone: "resnet34"
    weights: true
    lr: 1e-3
    patience: 2
    in_channels: 4
    num_classes: 14
    num_filters: 64
    ignore_index: null
data:
  class_path: NAIPChesapeakeDataModule
  init_args:
    batch_size: 32
    num_workers: 4
    patch_size: 32
  dict_kwargs:
    naip_root: "data/naip"
    chesapeake_root: "data/chesapeake/BAYWIDE"
