program:
  experiment_name: "naip_chesapeake_test"
  overwrite: True
trainer:
  min_epochs: 15
experiment:
  task: "naipchesapeake"
  module:
    loss: "ce"
    segmentation_model: "deeplabv3+"
    encoder_name: "resnet34"
    encoder_weights: "imagenet"
    encoder_output_stride: 16
    learning_rate: 1e-3
    learning_rate_schedule_patience: 2
    in_channels: 4
    num_classes: 14
    num_filters: 64
    ignore_index: null
  datamodule:
    naip_root_dir: "data/naip"
    chesapeake_root_dir: "data/chesapeake/BAYWIDE"
    batch_size: 32
    num_workers: 4
    patch_size: 32
