module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  loss: "ce"
  model: "deeplabv3+"
  backbone: "resnet34"
  weights: "imagenet"
  learning_rate: 1e-3
  learning_rate_schedule_patience: 2
  in_channels: 4
  num_classes: 14
  num_filters: 64
  ignore_index: null

datamodule:
  _target_: torchgeo.datamodules.NAIPChesapeakeDataModule
  naip_root: "data/naip"
  chesapeake_root: "data/chesapeake/BAYWIDE"
  batch_size: 32
  num_workers: 4
  patch_size: 32

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices: 1
  min_epochs: 15
  max_epochs: 40