module:
  _target_: torchgeo.trainers.ObjectDetectionTask
  model: "faster-rcnn"
  backbone: "resnet50"
  num_classes: 2
  learning_rate: 1.2e-4
  learning_rate_schedule_patience: 6
  verbose: false

datamodule:
  _target_: torchgeo.datamodules.NASAMarineDebrisDataModule
  root: "data/nasamr/nasa_marine_debris"
  batch_size: 4
  num_workers: 6
  val_split_pct: 0.2
