trainer:
  min_epochs: 15
  max_epochs: 40
model:
  class_path: ObjectDetectionTask
  init_args:
    model: "faster-rcnn"
    backbone: "resnet50"
    num_classes: 2
    lr: 1.2e-4
    patience: 6
data:
  class_path: NASAMarineDebrisDataModule
  init_args:
    batch_size: 4
    num_workers: 6
    val_split_pct: 0.2
  dict_kwargs:
    root: "data/nasamr/nasa_marine_debris"
