program:
  seed: 0
  overwrite: True

trainer:
  gpus: 1
  min_epochs: 5
  max_epochs: 100
  auto_lr_find: False
  benchmark: True

experiment:
  task: "nasa_marine_debris"
  name: "nasa_marine_debris_test"
  module:
    model: "faster-rcnn"
    backbone: "resnet50"
    pretrained: True
    num_classes: 2
    learning_rate: 1.2e-4
    learning_rate_schedule_patience: 6
    verbose: false
  datamodule:
    root: "data/nasamr/nasa_marine_debris"
    batch_size: 4
    num_workers: 56
    val_split_pct: 0.2
