trainer:
  gpus: 1
  min_epochs: 20
  max_epochs: 500
  benchmark: True
experiment:
  task: "oscd"
  module:
    loss: "jaccard"
    model: "unet"
    backbone: "resnet18"
    weights: null
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    verbose: false
    in_channels: 26
    num_classes: 2
    num_filters: 256
    ignore_index: 0
  datamodule:
    root: "data/oscd"
    num_tiles_per_batch: 32
    num_patches_per_tile: 128
    patch_size: 64
    val_split_pct: 0.1
    num_workers: 4
