trainer:
  gpus: 1
  min_epochs: 20
  max_epochs: 500
  benchmark: True
experiment:
  task: "oscd"
  module:
    loss: "jaccard"
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: null
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    verbose: false
    in_channels: 26
    num_classes: 2
    num_filters: 256
    ignore_index: 0
  datamodule:
    root_dir: "data/oscd"
    batch_size: 32
    num_workers: 4
    val_split_pct: 0.1
    bands: "all"
    pad_size:
    - 1028
    - 1028
    num_patches_per_tile: 128
