trainer:
  min_epochs: 15
  max_epochs: 40
model:
  class_path: BYOLTask
  init_args:
    in_channels: 12
    backbone: "resnet18"
    weights: True
    lr: 1e-3
    patience: 6
    optimizer: "Adam"
data:
  class_path: SeasonalContrastS2DataModule
  init_args:
    batch_size: 64
    num_workers: 16
  dict_kwargs:
    root: "data/seco"
    version: "100k"
    seasons: 2
    bands: ["B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B8A", "B9", "B11", "B12"]
