trainer:
  accelerator: gpu
  devices: 1
  min_epochs: 10
  max_epochs: 40
  benchmark: True
experiment:
  task: "seco"
  module:
    in_channels: 12
  datamodule:
    root: "data/seco"
    version: "100k"
    seasons: 2
    bands: ["B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B8A", "B9", "B11", "B12"]
    batch_size: 64
    num_workers: 16
