module:
  _target_: torchgeo.trainers.BYOLTask
  in_channels: 12
  backbone: "resnet18"
  weights: True
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6
  optimizer: "Adam"

datamodule:
  _target_: torchgeo.datamodules.SeasonalContrastS2DataModule
  root: "data/seco"
  version: "100k"
  seasons: 2
  bands: ["B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B8A", "B9", "B11", "B12"]
  batch_size: 64
  num_workers: 16

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices: 1
  min_epochs: 15
  max_epochs: 40
