module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  loss: "ce"
  model: "unet"
  backbone: "resnet18"
  weights: null
  learning_rate: 1e-3
  learning_rate_schedule_patience: 2
  in_channels: 15
  num_classes: 11
  ignore_index: null

datamodule:
  _target_: torchgeo.datamodules.SEN12MSDataModule
  root: "data/sen12ms"
  band_set: "all"
  batch_size: 32
  num_workers: 4

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices: 1
  min_epochs: 15
  max_epochs: 40
