program:  # These are experiment level arguments
  experiment_name: sen12ms_test
  overwrite: True

trainer:  # These are all the arguments that will be passed to the pl.Trainer
  min_epochs: 15

task:  # These are all the arguments that will be used to create an appropriate task
  name: sen12ms
  learning_rate: 1e-3
  learning_rate_schedule_patience: 2
