trainer:
  min_epochs: 15
  max_epochs: 40
model:
  class_path: SemanticSegmentationTask
  init_args:
    loss: "ce"
    model: "unet"
    backbone: "resnet18"
    weights: null
    lr: 1e-3
    patience: 2
    in_channels: 15
    num_classes: 11
    ignore_index: null
data:
  class_path: SEN12MSDataModule
  init_args:
    batch_size: 32
    num_workers: 4
  dict_kwargs:
    root: "data/sen12ms"
    band_set: "all"
