trainer:
  gpus: 1  # single GPU training
  min_epochs: 20
  max_epochs: 100
  benchmark: True

experiment:
  task: "so2sat"
  module:
    loss: "focal"
    classification_model: "resnet18"
    learning_rate: 1e-2
    learning_rate_schedule_patience: 6
  datamodule:
    batch_size: 128
    num_workers: 6
