module:
  _target_: SemanticSegmentationTask
  loss: "ce"
  model: "unet"
  backbone: "resnet18"
  weights: "imagenet"
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6
  in_channels: 3
  num_classes: 3
  ignore_index: 0

datamodule:
  _target_: SpaceNet1DataModule
  root: "data/spacenet"
  batch_size: 32
  num_workers: 4