module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  loss: "ce"
  model: "unet"
  backbone: "resnet18"
  weights: "imagenet"
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6
  in_channels: 3
  num_classes: 3
  ignore_index: 0

datamodule:
  _target_: torchgeo.datamodules.SpaceNet1DataModule
  root: "data/spacenet"
  batch_size: 32
  num_workers: 4

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices: 1
  min_epochs: 15
  max_epochs: 40
