program:
  overwrite: False
trainer:
  gpus: [3]
  min_epochs: 50
  max_epochs: 200
  benchmark: True
experiment:
  name: "spacenet-example"
  task: "sen12ms"
  module:
    loss: "ce"
    model: "unet"
    backbone: "resnet18"
    weights: "imagenet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    in_channels: 3
    num_classes: 3
    ignore_index: 0
  datamodule:
    root: "data/spacenet"
    batch_size: 32
    num_workers: 4
