module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  model: "unet"
  backbone: "resnet18"
  weights: null
  in_channels: 7
  num_classes: 14
  loss: "ce"
  ignore_index: 0
  lr: 1e-3
  patience: 6

datamodule:
  _target_: torchgeo.datamodules.SSL4EOLBenchmarkDataModule
  root: "data/ssl4eo_benchmark"
  sensor: "oli_sr"
  product: "nlcd"
  classes: [0, 11, 21, 22, 31, 41, 42, 43, 52, 71, 81, 82, 90, 95]
  batch_size: 64
  num_workers: 16

trainer:
  _target_: lightning.pytorch.Trainer
  min_epochs: 20
  max_epochs: 100
