module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  model: "unet"
  backbone: "resnet18"
  weights: null
  in_channels: 7
  num_classes: 18
  loss: "ce"
  ignore_index: 0
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6

datamodule:
  _target_: torchgeo.datamodules.SSL4EOLBenchmarkDataModule
  root: "data/ssl4eo_benchmark"
  sensor: "tm_toa"
  product: "cdl"
  classes: [0, 1, 5, 24, 36, 37, 61, 111, 121, 122, 131, 141, 142, 143, 152, 176, 190, 195]
  batch_size: 64
  num_workers: 16

trainer:
  _target_: lightning.pytorch.Trainer
  min_epochs: 20
  max_epochs: 100
