trainer:
  accelerator: gpu
  devices: 1
  min_epochs: 10
  max_epochs: 40
  benchmark: True
experiment:
  task: classification
  dataset: ucmerced
  module:
    loss: "ce"
    model: "resnet18"
    weights: null
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    in_channels: 3
    num_classes: 21
  datamodule:
    root: "data/ucmerced"
    batch_size: 128
    num_workers: 4
