trainer:
  min_epochs: 15
  max_epochs: 40
model:
  class_path: ClassificationTask
  init_args:
    loss: "ce"
    model: "resnet18"
    weights: null
    lr: 1e-3
    patience: 6
    in_channels: 3
    num_classes: 21
data:
  class_path: UCMercedDataModule
  init_args:
    batch_size: 128
    num_workers: 4
  dict_kwargs:
    root: "data/ucmerced"
