module:
  _target_: ClassificationTask
  loss: "ce"
  model: "resnet18"
  weights: null
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6
  in_channels: 3
  num_classes: 21

datamodule:
  _target_: UCMercedDataModule
  root: "data/ucmerced"
  batch_size: 128
  num_workers: 4