trainer:
  accelerator: gpu
  devices: 1
  min_epochs: 15
  max_epochs: 100
  default_root_dir: output/vhr10

model:
  class_path: ObjectDetectionTask
  init_args:
    model: "faster-rcnn"
    backbone: "resnet50"
    num_classes: 11
    lr: 3.0e-5
    patience: 20

data:
  class_path: VHR10DataModule
  init_args:
    batch_size: 4
    num_workers: 56
    patch_size: 512
    val_split_pct: 0.2
  dict_kwargs:
    root: "data/vhr10"
