experiment:
  task: "ssl"
  name: "test_byol"
  module:
    model: "byol"
    encoder: "resnet18"
    input_channels: 4
    imagenet_pretraining: True
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
  datamodule:
    batch_size: 64
    num_workers: 6
    train_splits:
      - "de-train"
    val_splits:
      - "de-val"
    test_splits:
      - "de-test"
