program:
  data_dir: "tests/data/chesapeake/cvpr"
experiment:
  task: "chesapeake_cvpr"
  module:
    loss: "ce"
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    encoder_output_stride: 16
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    in_channels: 4
    num_classes: 7
    num_filters: 256
  datamodule:
    train_state: "de"
    patches_per_tile: 200
    patch_size: 256
    batch_size: 64
    num_workers: 4
    num_classes: ${experiment.module.num_classes}
