program:
  data_dir: "tests/data/cowc_counting"
experiment:
  task: cowc_counting
  module:
    model: resnet18
    learning_rate: 1e-3
    learning_rate_schedule_patience: 2
  datamodule:
    batch_size: 32
    num_workers: 4
