experiment:
  task: cowc_counting
  module:
    model: resnet18
    learning_rate: 1e-3
    learning_rate_schedule_patience: 2
  datamodule:
    root_dir: "tests/data/cowc_counting"
    batch_size: 32
