experiment:
  task: "cyclone"
  module:
    model: "resnet18"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 2
    pretrained: False
  datamodule:
    root_dir: "tests/data/cyclone"
    batch_size: 32
    num_workers: 0
