experiment:
  task: "etci2021"
  module:
    loss: "ce"
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    in_channels: 7
    num_classes: 2
    ignore_zeros: True
  datamodule:
    root_dir: "tests/data/etci2021"
    batch_size: 32
    num_workers: 0
