experiment:
  task: "eurosat"
  module:
    loss: "ce"
    classification_model: "resnet18"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    weights: "random"
    in_channels: 13
    num_classes: 10
  datamodule:
    root_dir: "tests/data/eurosat"
    batch_size: 1
    num_workers: 0
