experiment:
  task: "naipchesapeake"
  module:
    loss: "ce"
    segmentation_model: "deeplabv3+"
    encoder_name: "resnet34"
    encoder_weights: "imagenet"
    encoder_output_stride: 16
    learning_rate: 1e-3
    learning_rate_schedule_patience: 2
    in_channels: 4
    num_classes: 13
    num_filters: 64
  datamodule:
    batch_size: 32
    num_workers: 4
