experiment:
  task: "oscd"
  module:
    loss: "jaccard"
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: null
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    verbose: false
    in_channels: 26
    num_classes: 2
    num_filters: 1
    ignore_zeros: True
  datamodule:
    root_dir: "tests/data/oscd"
    batch_size: 1
    num_workers: 0
    val_split_pct: 0.5
    bands: "all"
    pad_size:
      - 64
      - 64
    num_patches_per_tile: 1
