experiment:
  task: "sen12ms"
  module:
    loss: "ce"
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    encoder_output_stride: 16
    learning_rate: 1e-3
    learning_rate_schedule_patience: 2
    in_channels: 15
    num_classes: 11
    ignore_zeros: False
  datamodule:
    root_dir: "tests/data/sen12ms"
    batch_size: 32
    num_workers: 0
