experiment:
  task: "sen12ms"
  module:
    loss: "focal"
    segmentation_model: "fcn"
    num_filters: 1
    encoder_name: "resnet18"
    encoder_weights: null
    encoder_output_stride: 16
    learning_rate: 1e-3
    learning_rate_schedule_patience: 2
    in_channels: 2
    num_classes: 11
    ignore_zeros: False
  datamodule:
    root_dir: "tests/data/sen12ms"
    band_set: "s1"
    batch_size: 1
    num_workers: 0
    seed: 0
