experiment:
  task: "so2sat"
  module:
    loss: "ce"
    classification_model: "resnet18"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    weights: "random"
    in_channels: 3
    num_classes: 17
  datamodule:
    root_dir: "tests/data/so2sat"
    batch_size: 128
    num_workers: 0
    bands: "rgb"
