experiment:
  task: "ucmerced"
  module:
    loss: "ce"
    classification_model: "resnet18"
    weights: "random"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    in_channels: 3
    num_classes: 2
  datamodule:
    root_dir: "tests/data/ucmerced"
    batch_size: 1
    num_workers: 0
