# Copyright (c) TorchGeo Contributors. All rights reserved.
# Licensed under the MIT License.

index = [
    'TorchGeo',
    'eo-learn',
    'Raster Vision',
    'DeepForest',
    'samgeo',
    'TerraTorch',
    'SITS',
    'srai',
    'scikit-eo',
    'geo-bench',
    'GeoAI',
    'OTBTF',
    'GeoDeep',
]

name_to_pypi = {
    'TorchGeo': 'torchgeo',
    'eo-learn': 'eo-learn',
    'Raster Vision': 'rastervision',
    'DeepForest': 'deepforest',
    'samgeo': 'segment-geospatial',
    'TerraTorch': 'terratorch',
    'SITS': 'pysits',
    'srai': 'srai',
    'scikit-eo': 'scikeo',
    'geo-bench': 'geobench',
    'GeoAI': 'geoai-py',
    'GeoDeep': 'geodeep',
}
name_to_cran = {'SITS': 'sits'}
name_to_conda = {
    'TorchGeo': 'torchgeo',
    'eo-learn': 'eo-learn',
    'Raster Vision': 'rastervision-core',
    'DeepForest': 'deepforest',
    'samgeo': 'segment-geospatial',
    'SITS': 'r-sits',
    'GeoAI': 'geoai',
}
name_to_github = {
    'SPy': ('spectralpython', 'spectral'),
    'OTB': ('orfeotoolbox', 'OTB'),
    'DeepOSM': ('trailbehind', 'DeepOSM'),
    'DeepNetsForEO': ('nshaud', 'DeepNetsForEO'),
    'SITS': ('e-sensing', 'sits'),
    'Raster Vision': ('azavea', 'raster-vision'),
    'DeepHyperX': ('nshaud', 'DeepHyperX'),
    'Pyinterpolate': ('DataverseLabs', 'pyinterpolate'),
    'OTBTF': ('remicres', 'otbtf'),
    'eo-learn': ('sentinel-hub', 'eo-learn'),
    'RoboSat': ('mapbox', 'robosat'),
    'spopt': ('pysal', 'spopt'),
    'DELTA': ('nasa', 'delta'),
    'TorchSat': ('sshuair', 'torchsat'),
    'Solaris': ('CosmiQ', 'solaris'),
    'AIDE': ('microsoft', 'aerial_wildlife_detection'),
    'AiTLAS': ('biasvariancelabs', 'aitlas'),
    'DeepForest': ('weecology', 'DeepForest'),
    'ML4Floods': ('spaceml-org', 'ml4floods'),
    'TorchGeo': ('torchgeo', 'torchgeo'),
    'geo-bench': ('ServiceNow', 'geo-bench'),
    'torchrs': ('isaaccorley', 'torchrs'),
    'Myria3D': ('IGNF', 'myria3d'),
    'PaddleRS': ('PaddlePaddle', 'PaddleRS'),
    'GeoTorchAI': ('wherobots', 'GeoTorchAI'),
    'Raster4ML': ('souravbhadra', 'raster4ml'),
    'srai': ('kraina-ai', 'srai'),
    'Moonshine': ('moonshinelabs-ai', 'moonshine-remote-sensing'),
    'samgeo': ('opengeos', 'segment-geospatial'),
    'geodl': ('maxwell-geospatial', 'geodl'),
    'GeoAI': ('opengeos', 'geoai'),
    'scikit-eo': ('yotarazona', 'scikit-eo'),
    'TerraTorch': ('IBM', 'terratorch'),
    'GeoDeep': ('uav4geo', 'GeoDeep'),
    'GeoTessera': ('ucam-eo', 'geotessera'),
}
name_to_codecov = {
    'TorchGeo': ('gh', 'torchgeo', 'torchgeo'),
    'eo-learn': ('gh', 'sentinel-hub', 'eo-learn'),
    'SITS': ('gh', 'e-sensing', 'sits'),
    'srai': ('gh', 'kraina-ai', 'srai'),
}
