name: isort
on:
  push:
    branches:
    - main
    paths:
    - '**.py'
    - 'pyproject.toml'
    - '.github/workflows/isort.yaml'
  pull_request:
    branches:
    - main
    paths:
    - '**.py'
    - 'pyproject.toml'
    - '.github/workflows/isort.yaml'
jobs:
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install isort
      run: pip install isort[colors]>=4.3.5
    - name: Run isort checks
      run: isort . --check --diff
