name: "labeler"
on:
- pull_request_target
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4.2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
