name: "labeler"
on:
- pull_request_target
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v4.1.3
    - name: Add label
      uses: actions/labeler@v5.0.0
      with:
        sync-labels: true
