name: pytest
on:
  push:
    branches:
    - main
    paths:
    - '**.py'
    - 'requirements.txt'
    - '.github/workflows/pytest.yaml'
  pull_request:
    branches:
    - main
    paths:
    - '**.py'
    - 'requirements.txt'
    - '.github/workflows/pytest.yaml'
jobs:
  pytest:
    name: pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython numpy  # needed for pycocotools
        conda install -c conda-forge rasterio  # needed for windows
        pip install -r requirements.txt
    - name: Run pytest checks
      run: pytest
