name: pytest
on:
  push:
    branches:
    - main
    paths:
    - '**.py'
    - 'requirements.txt'
    - '.github/workflows/pytest.yaml'
  pull_request:
    branches:
    - main
    paths:
    - '**.py'
    - 'requirements.txt'
    - '.github/workflows/pytest.yaml'
jobs:
  pytest:
    name: pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          # All OSes
          ~/conda_pkgs_dir
          # Linux
          ~/.cache/pip
          /var/cache/apt/archives
          # macOS
          ~/Library/Caches/pip
          ~/Library/Caches/Homebrew
          # Windows
          ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
        restore-keys: ${{ runner.os }}-python-${{ matrix.python-version }}-
    - name: Install apt dependencies
      run: sudo apt-get install unrar
      if: ${{ runner.os == 'Linux' }}
    - name: Install brew dependencies
      run: brew install rar
      if: ${{ runner.os == 'macOS' }}
    - name: Install conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
      if: ${{ runner.os == 'Windows' }}
    - name: Install conda dependencies
      run: conda install -c conda-forge rasterio
      if: ${{ runner.os == 'Windows' }}
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython numpy  # needed for pycocotools
        pip install -r requirements.txt
    - name: Run pytest checks
      run: pytest --cov=. --cov-report=term-missing
