name: release
on:
  push:
    branches:
      - release**
  pull_request:
    branches:
      - release**
defaults:
  run:
    shell: bash
jobs:
  integration:
    name: integration
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5.0.0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'
          enable-cache: true
      - name: Install dependencies
        run: uv sync --extra datasets --extra tests --torch-backend=auto
      - name: List dependencies
        run: uv pip list
      - name: Run integration checks
        run: |
          uv run pytest -m slow --durations=10 tests/samplers
          uv run pytest -m slow --durations=10 tests/trainers
          uv run python -m torchgeo --help
          uv run torchgeo --help
  notebooks:
    name: notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5.0.0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'
          enable-cache: true
      - name: Install dependencies
        run: |
          uv sync --extra docs --extra tests --torch-backend=auto
          uv add planetary_computer pystac tensorboard h5py scikit-learn
      - name: List dependencies
        run: uv pip list
      - name: Run notebook checks
        run: uv run pytest --nbmake --durations=10 docs/tutorials
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
